### ISSUE TITLE
IMPORTANG THING.

### ISSUE THREAD

**Issue by ZloyNick** [Muqsit/VanillaGenerator#8]
Fix SnowyGroundGenerator.

Add to __construct func "$this->setGroundMaterial(self::$AIR)", else snowy biomes coudnt be generate, because $groundMaterial is null. Tested. 

And so, Melons doesnt populates in Jungle, i dont remember how i was fixed it. Also, big mushrooms havent metadata parameter. They are always white)))

**Comment by ZloyNick** [comment]
Fatal error: Uncaught Error: Call to a member function getId() on null in D:\Dev\detreex-server\plugins\#Archinheim-master\src\muqsit\vanillagenerator\generator\ground\GroundGenerator.php:138
Stack trace:
#0 D:\Dev\detreex-server\plugins\#Archinheim-master\src\muqsit\vanillagenerator\generator\overworld\Normal.php(143): muqsit\vanillagenerator\generator\ground\GroundGenerator->generateTerrainColumn(Object(pocket
mine\level\SimpleChunkManager), Object(pocketmine\utils\Random), 0, 864, 140, -2.2105148196439)
#1 D:\Dev\detreex-server\plugins\#Archinheim-master\src\muqsit\vanillagenerator\generator\VanillaGenerator.php(111): muqsit\vanillagenerator\generator\overworld\Normal->generateChunkData(0, 54, Object(muqsit\va
nillagenerator\generator\VanillaBiomeGrid))
#2 D:\Dev\detreex-server\src\pocketmine\level\generator\GenerationTask.php(71): muqsit\vanillagenerator\generator\VanillaGenerator->generateChunk(0, 54)
#3 D:\Dev\detreex-server\src\pocketmine\scheduler\AsyncTask.php(43): pocketmine\level\generator\GenerationTask->onRun() in D:\Dev\detreex-server\plugins\#Archinheim-master\src\muqsit\vanillagenerator\generator\
ground\GroundGenerator.php on line 138
140


140 its a biome id. I was printed id to found problem class.
